cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    crio:
      email: crio77impex@gmail.com
      name: Crio IMPEX pvt Ltd
      password: $2b$12$Ym6DXui9dq0qKNeiV9n9KebOhn3c.TQmtHfaBlja7AySXHJvIXUbW
preauthorized:
  emails:
  - i@soumalya.in
