cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    crio:
      email: crio77impex@gmail.com
      name: Crio IMPEX pvt Ltd
      password: $2b$12$Bkdm0cDHhzgTCZJlXBkeDOaEBl//eRwiSt1TDd6b6eDJZFqsZIw62
    iamsoumalya:
      email: i@soumalya.in
      name: Soumalya Chowdhury
      password: $2b$12$Ii6k5ai3TSzE8.kVMbgu1eUxHYvpKPS9JBIlhOkMzziIpOP57lqw2
    s9862:
      email: soumalya9862@gmail.com
      name: Soumalya Chowdhury
      password: $2b$12$Viqug10FUNkZlEoQexHmE.oaFfYr1288c49NdyMS8ulTvBI36vATW
preauthorized:
  emails:
  - i@soumalya.in
